# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class reference_data_update(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def fix_genome_taxonomies(self, params, context=None):
        """
        :param params: instance of type "UpdateTaxaParams" -> structure:
           parameter "target_workspace" of String, parameter
           "selection_params" of String, parameter "bad_word" of String
        :returns: instance of type "UpdateTaxaResults" -> structure:
           parameter "results" of String
        """
        return self._client.call_method(
            'reference_data_update.fix_genome_taxonomies',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('reference_data_update.status',
                                        [], self._service_ver, context)
